create table users
(
    id bigint generated by default as identity
        constraint users_pkey primary key,
    name varchar(255),
    username varchar(255)
        constraint uk_users unique,
    password varchar(255)
);

insert into users (name, username, password)
values ('Admin', 'admin', 'admin'),
       ('Teacher1', 'teacher1', 'teacher1'),
       ('Teacher2', 'teacher2', 'teacher2'),
       ('Student1', 'student1', 'student1'),
       ('Student2', 'student2', 'student2');