create table enrols
(
    id bigint generated by default as identity
        constraint enrols_pkey primary key,
    enrol_date timestamp,
    course_id bigint
        constraint fk_enrols_courses
        references courses,
    user_id bigint
        constraint fk_enrols_users
        references users
);