create table resources
(
    id bigint generated by default as identity
        constraint resources_pkey primary key,
    title varchar(255),
    content varchar(255),
    user_id bigint
        constraint fk_resources_users references users
);

insert into resources (title, content, user_id)
values ('Resource1', 'Resource1 content', 2),
       ('Resource2', 'Resource2 content', 2),
       ('Resource3', 'Resource3 content', 2),
       ('Resource4', 'Resource4 content', 3);