create table users_roles
(
    id bigint generated by default as identity
        constraint users_roles_pkey primary key,
    user_id bigint not null
        constraint fk_users_roles_users
        references users,
    role_id bigint not null
        constraint fk_users_roles_roles
        references roles
);

insert into users_roles (user_id, role_id)
values (1, 1),
       (1, 2),
       (1, 3),
       (2, 2),
       (2, 3),
       (3, 2),
       (3, 3),
       (4, 3),
       (5, 3);